### PR TITLE
Add duration-before-trigger flag to alert creation and update

### PR DESCRIPTION
**Pull request by EtienneM**
Related to Scalingo/scalingo-alerter-service#93

### CODE REVIEW

**Comment by Soulou** [comment]
Example of output?

**Comment by EtienneM** [comment]
```
+-----------------------------------------+--------+----------------+--------+----------------------+----------+
|                   ID                    | ACTIVE | CONTAINER TYPE | METRIC |        LIMIT         | DURATION |
+-----------------------------------------+--------+----------------+--------+----------------------+----------+
| al-dc6450de-7331-486d-89a2-409e17424c80 | true   | web            | rpm    | triggers above 15.00 | 3m0s     |
+-----------------------------------------+--------+----------------+--------+----------------------+----------+
```

**Comment by Soulou** [comment]
Could we have this:

```
> ./cli -a gregfregegre alerts
+-----------------------------------------+--------+----------------+--------+----------------------+
|                   ID                    | ACTIVE | CONTAINER TYPE | METRIC |        TRIGGER       |
+-----------------------------------------+--------+----------------+--------+----------------------+
| al-dc6450de-7331-486d-89a2-409e17424c80 | true   | web            | rpm    | >= 15.00 (for 3m0s)  |
+-----------------------------------------+--------+----------------+--------+----------------------+
```

To me it's much clearer semantically, do you agree?

**Comment by EtienneM** [comment]
```
+-----------------------------------------+--------+----------------+--------+----------------+
|                   ID                    | ACTIVE | CONTAINER TYPE | METRIC |     LIMIT      |
+-----------------------------------------+--------+----------------+--------+----------------+
| al-dc6450de-7331-486d-89a2-409e17424c80 | true   | web            | rpm    | ≥ 15.00 (3m0s) |
+-----------------------------------------+--------+----------------+--------+----------------+
```

**Pull request merged**
