### PR TITLE
fix(notifiers): Unable to add a notifier when no collaborator are specified

### PR DESCRIPTION
**Pull request by aurelien-reeves-scalingo**
- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md

### CODE REVIEW

**Comment by aurelien-reeves-scalingo** [comment]
For info: the issue was due to the new `NewStringSlice` function to create a `StringSlice` flag. It considered the empty string as a not-nil default value. That resulted in the resulting `[]string` being an array filed with a single empty string

**Review by Soulou — APPROVED** [review]
@aurelien-reeves-scalingo Are there other StringSlice? Otherwise LGTM

**Comment by aurelien-reeves-scalingo** [comment]
> @aurelien-reeves-scalingo Are there other StringSlice? Otherwise LGTM

I did a global search to make sure all of them was fixed

**Comment by Soulou** [comment]
Great, let's merge it then!

**Pull request merged**
