### PR TITLE
Bump version 1.32.1

### PR DESCRIPTION
**Pull request by SCedricThomas**
- [ ] Add a changelog entry in the section "To Be Released" of CHANGELOG.md

### CODE REVIEW

**Review by EtienneM — CHANGES_REQUESTED** [review]
There is a new feature, I think it should lead to a new minor version to follow semver. Hence 1.33.0. WDYT?

**Comment by SCedricThomas** [comment]
Right

**Comment by SCedricThomas** [comment]
Close to have branch name matching the release version

**Comment by SCedricThomas** [comment]
Closed to have branch name matching the release version

**Pull request closed without merging**
