### PR TITLE
WIP: filter for all one-off

### PR DESCRIPTION
**Pull request by btrd**
fix https://github.com/Scalingo/cli/issues/799

### CODE REVIEW

**Comment by btrd** [comment]
From my local test, it doesn't work, maybe the [log-service](https://github.com/Scalingo/logs-service/) doesn't allow this filter ?

**Comment by Soulou** [comment]
I confirm, this filter is not allowed, why:

It's filtered by the container_types

**Review by EtienneM — COMMENTED** [review]
Currently our backend does not support this syntax. Is there a reason that the customer don't use `grep`? I mean, it should be possible to do:

```
scalingo --app my-app logs | grep one-off
```
WDYT?

**Comment by btrd** [comment]
- to prevent from having to download every log lines
- grep doesn't work when using -f
- if `web` & `web-1` if valid, there is no reason (from the point of view of the client) that `one-off-1` work but not `one-off`

I think we can close this PR, I let you decide what to do with the issue.

**Comment by btrd** [comment]
Need a change in https://github.com/Scalingo/logs-service to work.

**Pull request closed without merging**
