### PR TITLE
Notification commands: List/Add/Remove

### PR DESCRIPTION
**Pull request by utay**
Notification commands still under construction.

### CODE REVIEW

**Comment by utay** [comment]
Remove and List commands work great now

**Comment by Soulou** [comment]
:+1:

**Comment by Soulou** [comment]
1. You need to me `master` into this branch to get this mergeable

2. Please rebase all your commit and squash them to one or two, it's a bit messy now

**Comment by utay** [comment]
Done! I work on the Add command now.

**Pull request merged**
