### PR TITLE
feat: allow log to be filter with routeur

### PR DESCRIPTION
**Pull request by btrd**

### CODE REVIEW

**Review by Soulou — APPROVED** [review]

**Comment by Soulou** [comment]
Please update CHANGELOG

**Review by Soulou — CHANGES_REQUESTED** [review]
(For the changelog of the project)

**Comment by EtienneM** [comment]
@btrd Out of curiosity, how did you open the PR? We configured a PR template (https://github.com/Scalingo/cli/blob/master/.github/pull_request_template.md) and I'm surprised it has not been used here :)

**Comment by btrd** [comment]
Oups, from the github cli `gh pr create -f -r soulou` -f to force the title/body maybe without this flag the template would have been shown to me.

**Review by EtienneM — APPROVED** [review]

**Review by Soulou — APPROVED** [review]

**Pull request merged**
